# -*- coding: utf-8 -*-
"""
Motor de Internacionalização (i18n) do TatschViewer 1.5.
Gerencia as preferências de idioma (PT-BR vs EN) e armazena o dicionário de traduções.
"""
import os
import json
from PyQt6.QtCore import QStandardPaths

class Tradutor:
    _instance = None

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(Tradutor, cls).__new__(cls, *args, **kwargs)
            cls._instance._inicializado = False
        return cls._instance

    def __init__(self):
        if self._inicializado:
            return
        self._inicializado = True
        
        # Obter pasta de cache oculta para salvar config.json
        cache_dir = QStandardPaths.writableLocation(QStandardPaths.StandardLocation.GenericCacheLocation)
        if not cache_dir:
            cache_dir = os.path.expanduser("~")
        
        self.cache_folder = os.path.join(cache_dir, ".tatschviewer_cache")
        os.makedirs(self.cache_folder, exist_ok=True)
        self.config_file = os.path.join(self.cache_folder, "config.json")
        
        # Idioma padrão
        self.idioma = "pt"
        self.carregar_config()
        
        # Base de Dados de Traduções PT / EN
        self.dicionario = {
            # --- Splash Screen e EULA (main.py) ---
            "status_iniciando": {
                "pt": "Iniciando sistema...",
                "en": "Starting system..."
            },
            "status_carregando_modulos": {
                "pt": "Carregando o sistema...\nPor favor, aguarde.",
                "en": "Loading system...\nPlease wait."
            },
            "footer_copyright": {
                "pt": "© 2026 João Tatsch. Todos os direitos reservados.",
                "en": "© 2026 João Tatsch. All rights reserved."
            },
            "eula_titulo": {
                "pt": "Termo de Responsabilidade - TatschViewer 1.5",
                "en": "Terms of Responsibility - TatschViewer 1.5"
            },
            "eula_texto": {
                "pt": "AVISO LEGAL:\n\nO TatschViewer 1.5 é um software desenvolvido exclusivamente para fins de pesquisa, acadêmicos e revisão secundária.\n\nEle NÃO possui certificações regulatórias (ANVISA, FDA, CE) para diagnóstico clínico primário. O uso das informações geradas por este software é de inteira responsabilidade do profissional de saúde.\n\nVocê aceita estes termos?",
                "en": "LEGAL ADVISORY:\n\nTatschViewer 1.5 is software developed exclusively for research, academic, and secondary review purposes.\n\nIt DOES NOT have regulatory certifications (ANVISA, FDA, CE) for primary clinical diagnosis. The use of information generated by this software is the sole responsibility of the healthcare professional.\n\nDo you accept these terms?"
            },
            "msg_idioma_alterado": {
                "pt": "O idioma foi alterado. Por favor, reinicie o aplicativo para aplicar as mudanças.",
                "en": "Language has been changed. Please restart the application to apply the changes."
            },
            "msg_aviso_reinicio": {
                "pt": "Alteração de Idioma",
                "en": "Language Change"
            },
            "crash_titulo": {
                "pt": "Erro Crítico - TatschViewer 1.5",
                "en": "Critical Error - TatschViewer 1.5"
            },
            "crash_texto": {
                "pt": "Desculpe! O TatschViewer 1.5 encontrou uma falha fatal e precisa ser encerrado.\n\nUm relatório detalhado contendo a causa técnica do erro foi exportado para:\n'{caminho}'\n\nSe este problema continuar acontecendo, por favor envie o relatório acima para o suporte técnico.",
                "en": "We are sorry! TatschViewer 1.5 encountered a fatal crash and needs to be terminated.\n\nA detailed report containing the technical cause of the error has been exported to:\n'{caminho}'\n\nIf this issue persists, please send the above report to technical support."
            },
            
            # --- Toolbar & UI principal (interface.py) ---
            "app_title": {
                "pt": "TatschViewer - Visualizador DICOM",
                "en": "TatschViewer - DICOM Viewer"
            },
            "btn_abrir": {
                "pt": "Abrir Pasta",
                "en": "Open Folder"
            },
            "tip_abrir": {
                "pt": "Seleciona um diretório contendo arquivos DICOM",
                "en": "Select a directory containing DICOM files"
            },
            "btn_anonimizar": {
                "pt": "Anonimizar",
                "en": "Anonymize"
            },
            "tip_anonimizar": {
                "pt": "Anonimiza e exporta a série ativa para um novo diretório",
                "en": "Anonymizes and exports the active series to a new directory"
            },
            "btn_presets": {
                "pt": "Janelamento / Presets",
                "en": "Windowing / Presets"
            },
            "btn_mip": {
                "pt": "Modos de Projeção (MIP)",
                "en": "Projection Modes (MIP)"
            },
            "btn_layout": {
                "pt": "Layouts de Exibição",
                "en": "Display Layouts"
            },
            "tip_espessura": {
                "pt": "Espessura do Slab (MIP)",
                "en": "Slab Thickness (MIP)"
            },
            "btn_crosshair": {
                "pt": "Ativar Mira 3D (Crosshair)",
                "en": "Enable 3D Crosshair"
            },
            "btn_regua": {
                "pt": "Medida (Régua 3D)",
                "en": "Measure (3D Ruler)"
            },
            "btn_elipse": {
                "pt": "ROI (Elipse 3D)",
                "en": "ROI (3D Ellipse)"
            },
            "btn_reslice": {
                "pt": "Reslice Oblíquo",
                "en": "Oblique Reslice"
            },
            "btn_subtracao": {
                "pt": "Subt. Óssea",
                "en": "Bone Subtraction"
            },
            "btn_sync": {
                "pt": "Sincronizar Navegação (Scroll)",
                "en": "Sync Navigation (Scroll)"
            },
            "btn_disseccao": {
                "pt": "Dissecção",
                "en": "Dissection"
            },
            "btn_ajuda": {
                "pt": "❓ Ajuda",
                "en": "❓ Help"
            },
            "btn_sobre": {
                "pt": "ℹ️ Sobre",
                "en": "ℹ️ About"
            },
            "btn_idioma": {
                "pt": "🌐 PT / EN",
                "en": "🌐 PT / EN"
            },
            "status_pronto": {
                "pt": "Pronto",
                "en": "Ready"
            },
            "lbl_dicas_btn": {
                "pt": "ℹ️ Dicas de Navegação",
                "en": "ℹ️ Navigation Tips"
            },
            "lbl_series_dock": {
                "pt": "Séries de Imagens",
                "en": "Image Series"
            },
            "menu_visualizacao": {
                "pt": "Visualização",
                "en": "View"
            },
            "layout_1up": {
                "pt": "1-Up (Apenas Axial)",
                "en": "1-Up (Axial Only)"
            },
            "layout_3up": {
                "pt": "3-Up (MPR)",
                "en": "3-Up (MPR)"
            },
            "layout_3d": {
                "pt": "Apenas 3D",
                "en": "3D Only"
            },
            "layout_4up": {
                "pt": "4-Up (Padrão)",
                "en": "4-Up (Standard)"
            },
            
            # --- Submenus (interface.py) ---
            "subtracao_rapida": {
                "pt": "Subt. rápida",
                "en": "Fast subtraction"
            },
            "subtracao_lenta": {
                "pt": "Subt. lenta",
                "en": "Slow subtraction"
            },
            "disseccao_cubo": {
                "pt": "Cubo de interesse",
                "en": "Bounding box"
            },
            "disseccao_caixa": {
                "pt": "Caixa de Recorte",
                "en": "Crop Box"
            },
            "disseccao_aplicar": {
                "pt": "Aplicar Recorte",
                "en": "Apply Crop"
            },
            "disseccao_resetar": {
                "pt": "Resetar 3D",
                "en": "Reset 3D"
            },
            "disseccao_bisturi": {
                "pt": "Bisturi de Mão Livre",
                "en": "Freehand Scalpel"
            },
            "bisturi_desenhar": {
                "pt": "Desenhar Contorno",
                "en": "Draw Contour"
            },
            "bisturi_interior": {
                "pt": "Cortar interior",
                "en": "Cut inside"
            },
            "bisturi_exterior": {
                "pt": "Cortar exterior",
                "en": "Cut outside"
            },
            "bisturi_reset": {
                "pt": "Restaurar Original",
                "en": "Restore Original"
            },
            
            # --- Tópicos de Ajuda e Sobre (ajuda.py) ---
            "ajuda_abrir_lbl": {
                "pt": "Abrindo arquivos DICOM",
                "en": "Opening DICOM files"
            },
            "ajuda_abrir_val": {
                "pt": "Para abrir exames, você pode usar o botão 'Abrir Pasta' na barra de ferramentas ou simplesmente arrastar e soltar uma pasta DICOM (ou arquivo .zip) diretamente em qualquer tela do aplicativo. O sistema possui um cache inteligente que fará exames já vistos abrirem instantaneamente.",
                "en": "To open exams, you can use the 'Open Folder' button on the toolbar or simply drag and drop a DICOM folder (or .zip file) directly into any screen of the application. The system has a smart cache that will open previously loaded exams instantly."
            },
            "ajuda_anonimizador_lbl": {
                "pt": "Anonimizador",
                "en": "Anonymizer"
            },
            "ajuda_anonimizador_val": {
                "pt": "Remove todas as tags confidenciais do paciente (Nome, ID, Data) e reescreve o arquivo no rigoroso padrão DICOM Part 10. Selecione a série na lista à esquerda e clique no botão Anonimizar. Você pode exportar apenas a série ativa ou todas as séries do diretório.",
                "en": "Removes all confidential patient tags (Name, ID, Date) and rewrites the file to the strict DICOM Part 10 standard. Select the series in the left list and click the Anonymize button. You can export only the active series or all series in the directory."
            },
            "ajuda_multitelas_lbl": {
                "pt": "Usando múltiplas telas",
                "en": "Using multiple viewports"
            },
            "ajuda_multitelas_val": {
                "pt": "O TatschViewer permite a comparação de múltiplos exames (ex: Fase Sem Contraste vs Angio). Clique em uma série na lista lateral esquerda, mantenha o botão do mouse pressionado e arraste-a para dentro de qualquer um dos quadrantes de visualização.",
                "en": "TatschViewer allows the comparison of multiple exams (e.g., Non-Contrast vs Angio phase). Click on a series in the left list, keep the mouse button pressed, and drag and drop it into any of the display viewports."
            },
            "ajuda_sync_lbl": {
                "pt": "Botão de Sincronizar (Toggle)",
                "en": "Sync Button (Toggle)"
            },
            "ajuda_sync_val": {
                "pt": "Representado pelo ícone de Corrente (🔗). Quando ativado, rolar a roda do mouse (scroll) em uma tela fará com que todas as outras telas acompanhem o movimento fisicamente (em milímetros), garantindo o alinhamento anatômico perfeito entre exames de diferentes resoluções.",
                "en": "Represented by the Chain icon (🔗). When enabled, scrolling the mouse wheel in one viewport will make all other viewports follow the movement physically (in millimeters), ensuring perfect anatomical alignment between exams of different resolutions."
            },
            "ajuda_janela_lbl": {
                "pt": "Janelamento",
                "en": "Windowing"
            },
            "ajuda_janela_val": {
                "pt": "Ajusta o Contraste (WW) e Brilho (WL). Você pode usar o botão de Presets na barra superior para seleções rápidas (ex: Cérebro, Osso) ou clicar com o Botão Esquerdo do mouse sobre o fundo da imagem e arrastar para ajustar manualmente.",
                "en": "Adjusts Contrast (WW) and Brightness (WL). You can use the Presets button on the top toolbar for quick selections (e.g., Brain, Bone) or click the Left Mouse Button on the background of the image and drag to adjust manually."
            },
            "ajuda_mip_lbl": {
                "pt": "MIP, MinIP e Average",
                "en": "MIP, MinIP, and Average"
            },
            "ajuda_mip_val": {
                "pt": "Ferramentas de Projeção de Intensidade. Use o menu 'MIP' para ativar. MIP destaca vasos e ossos (estruturas densas); MinIP destaca vias aéreas (baixa densidade); Average cria uma média. Ajuste a espessura da projeção (Slab) na caixa de milímetros ao lado.",
                "en": "Intensity Projection Tools. Use the 'MIP' menu to enable. MIP highlights vessels and bones (dense structures); MinIP highlights airways (low density); Average creates an average. Adjust the projection slab thickness in the millimeter box next to it."
            },
            "ajuda_reslice_lbl": {
                "pt": "Reslice",
                "en": "Reslice"
            },
            "ajuda_reslice_val": {
                "pt": "Ative o botão de Reslice para reconstrução oblíqua livre. Nas telas 2D, clique e segure nos eixos coloridos próximos às bordas para rotacionar o plano. Clique no centro exato da cruz para arrastar o ponto de pivô.",
                "en": "Enable the Reslice button for free oblique reconstruction. On 2D viewports, click and hold on the colored axes near the edges to rotate the plane. Click on the exact center of the crosshairs to drag the pivot point."
            },
            "ajuda_crosshair_lbl": {
                "pt": "Crosshair (Mira)",
                "en": "Crosshair (Target)"
            },
            "ajuda_crosshair_val": {
                "pt": "Ative o botão ⌖. Ao clicar em qualquer estrutura no 2D, as outras duas visões ortogonais e o modelo 3D saltarão instantaneamente para a exata coordenada 3D apontada. Atalho rápido: Segure a tecla 'C'.",
                "en": "Enable the ⌖ button. By clicking on any structure in 2D, the other two orthogonal viewports and the 3D model will instantly jump to the exact 3D coordinate clicked. Quick shortcut: Hold the 'C' key."
            },
            "ajuda_regua_lbl": {
                "pt": "Régua",
                "en": "Ruler"
            },
            "ajuda_regua_val": {
                "pt": "Ferramenta de distância linear. Ative o botão da régua, clique e segure o botão esquerdo no ponto inicial, arraste até o ponto final e solte. Para apagar, passe o mouse sobre ela e aperte a tecla 'Delete'.",
                "en": "Linear distance tool. Enable the ruler button, click and hold the left button on the starting point, drag to the ending point, and release. To delete, hover over it and press the 'Delete' key."
            },
            "ajuda_elipse_lbl": {
                "pt": "Elipse (ROI)",
                "en": "Ellipse (ROI)"
            },
            "ajuda_elipse_val": {
                "pt": "Ferramenta de Região de Interesse. Funciona de forma similar à Régua, mas desenha um círculo. Ela calcula automaticamente a Área em mm², além da Densidade Máxima, Mínima e Média em Unidades Hounsfield (HU) dos pixels englobados.",
                "en": "Region of Interest tool. Works similarly to the Ruler, but draws a circle. It automatically calculates the Area in mm², in addition to the Maximum, Minimum, and Mean Density in Hounsfield Units (HU) of the enclosed pixels."
            },
            "ajuda_subtracao_rapida_lbl": {
                "pt": "Subtração Óssea > Rápida",
                "en": "Bone Subtraction > Fast"
            },
            "ajuda_subtracao_rapida_val": {
                "pt": "Utiliza apenas a fase contrastada (Single-Scan). É um processo de segundos que isola a árvore vascular intracraniana e cervical através de algoritmos de morfologia matemática e sementes de inundação (Region Growing). Ideal para rotinas de emergência.",
                "en": "Uses only the contrasted phase (Single-Scan). It is a process of seconds that isolates the intracranial and cervical vascular tree through mathematical morphology algorithms and region growing seeds. Ideal for emergency routines."
            },
            "ajuda_subtracao_lenta_lbl": {
                "pt": "Subtração Óssea > Lenta",
                "en": "Bone Subtraction > Slow"
            },
            "ajuda_subtracao_lenta_val": {
                "pt": "Utiliza a técnica clássica de Subtração Digital (DSA). Demanda mais poder computacional e tempo. Requer a fase Sem Contraste e a Angio. Executa o registro espacial rígido (alinhamento). Possui limitações caso o paciente tenha movimentado o pescoço entre as aquisições.",
                "en": "Uses the classic Digital Subtraction Angiography (DSA) technique. Demands more computational power and time. Requires both the Non-Contrast phase and the Angio phase. Performs rigid spatial registration (alignment). Has limitations if the patient moved their neck between acquisitions."
            },
            "ajuda_disseccao_cubo_lbl": {
                "pt": "Dissecção > Cubo de Interesse",
                "en": "Dissection > Bounding Box"
            },
            "ajuda_disseccao_cubo_val": {
                "pt": "Gera uma caixa envolvente (Bounding Box). Arraste as paredes da caixa nas visões 2D para 'recortar' o modelo 3D em tempo real. Essencial para decaptar a calvária e observar o polígono de Willis de cima.",
                "en": "Generates a bounding box. Drag the walls of the box on the 2D viewports to 'crop' the 3D model in real time. Essential to decapitate the skullcap and observe the circle of Willis from above."
            },
            "ajuda_disseccao_bisturi_lbl": {
                "pt": "Dissecção > Bisturi de Mão livre",
                "en": "Dissection > Freehand Scalpel"
            },
            "ajuda_disseccao_bisturi_val": {
                "pt": "Ferramenta de extirpação. Ative e desenhe um polígono livre com o mouse sobre a tela 3D ou 2D fechando o círculo. Tudo o que estiver dentro do desenho será apagado da memória volumétrica.",
                "en": "Extirpation tool. Enable and draw a free polygon with the mouse over the 3D or 2D screen, closing the circle. Everything inside the drawing will be erased from volumetric memory."
            },
            
            # --- Sobre o Programa ---
            "sobre_intuito_lbl": {
                "pt": "Intuito do Programa",
                "en": "Project Purpose"
            },
            "sobre_intuito_val": {
                "pt": "O TatschViewer nasceu de uma missão social e médica: auxiliar hospitais, clínicas e profissionais que não possuem um visualizador DICOM nativo ou não dispõem de recursos financeiros para licenciar softwares comerciais de alto custo. Este programa é de código aberto (Open Source) e está disponível gratuitamente para uso, democratizando o acesso à neuroimagem de alta performance computacional.",
                "en": "TatschViewer was born from a social and medical mission: to assist hospitals, clinics, and professionals who do not have a native DICOM viewer or do not have financial resources to license high-cost commercial software. This program is Open Source and is available free of charge for use, democratizing access to high-performance computational neuroimaging."
            },
            "sobre_autor_lbl": {
                "pt": "Sobre o Autor",
                "en": "About the Author"
            },
            "sobre_autor_val": {
                "pt": "Dr. João Fellipe Santos Tatsch é médico neurologista formado pela Escola Superior de Ciências da Saúde (ESCS-DF), com período sanduíche na University of Toronto (Canadá), onde realizou estágio em neurocirurgia no Toronto Western Hospital. Concluiu sua Residência Médica em Neurologia e Fellowship em Neurologia Geral no Hospital Santa Marcelina (SP). Atualmente, atua como Neurologista na rede pública do Distrito Federal (Hospital Regional do Gama e Santa Maria). Aliando sua expertise clínica à engenharia de software, desenvolve ferramentas tecnológicas para aprimorar a prática médica.",
                "en": "Dr. João Fellipe Santos Tatsch is a neurologist graduated from Escola Superior de Ciências da Saúde (ESCS-DF), with a sandwich period at the University of Toronto (Canada), where he completed a neurosurgery clerkship at Toronto Western Hospital. He completed his Neurology Residency and General Neurology Fellowship at Hospital Santa Marcelina (SP). Currently, he works as a Neurologist in the public health system of the Distrito Federal (Hospital Regional do Gama and Santa Maria). Combining his clinical expertise with software engineering, he develops technological tools to enhance medical practice."
            },
            "sobre_site_lbl": {
                "pt": "Site Oficial",
                "en": "Official Site"
            },
            "sobre_site_val": {
                "pt": "Acesse nosso site para novidades, atualizações e documentação:\n\n🌐 www.joaotatsch.com.br\n\n.",
                "en": "Visit our website for news, updates, and documentation:\n\n🌐 www.joaotatsch.com.br\n\n."
            },
            "sobre_contato_lbl": {
                "pt": "Entre em Contato",
                "en": "Contact Us"
            },
            "sobre_contato_val": {
                "pt": "Dúvidas, sugestões ou parcerias? Entre em contato diretamente com o desenvolvedor:\n\n📧 E-mail: neurologistajoao@gmail.com",
                "en": "Questions, suggestions, or partnerships? Contact the developer directly:\n\n📧 E-mail: neurologistajoao@gmail.com"
            }
        }

    def carregar_config(self):
        if os.path.exists(self.config_file):
            try:
                with open(self.config_file, "r", encoding="utf-8") as f:
                    config = json.load(f)
                    self.idioma = config.get("idioma", "pt")
            except Exception as e:
                print(f"[TRADUTOR] Erro ao carregar config: {e}")

    def salvar_config(self):
        try:
            with open(self.config_file, "w", encoding="utf-8") as f:
                json.dump({"idioma": self.idioma}, f, indent=2)
        except Exception as e:
            print(f"[TRADUTOR] Erro ao salvar config: {e}")

    def definir_idioma(self, idioma):
        if idioma in ("pt", "en"):
            self.idioma = idioma
            self.salvar_config()

    def tr(self, chave):
        trad_dict = self.dicionario.get(chave)
        if not trad_dict:
            return chave
        return trad_dict.get(self.idioma, chave)

# Instanciação Singleton Global e atalho de função tr
_tradutor_global = Tradutor()

def tr(chave):
    return _tradutor_global.tr(chave)


# Estruturas HTML de Dicas de Navegação para interface.py
HTML_DICAS_NAVEGACAO_PT = (
    "<div style='color: #aaaaaa;'>"
    "<table width='100%' align='center' cellpadding='15' style='border-collapse: collapse;'>"
    "<tr>"
    "<td width='50%' valign='top' style='border-right: 1px solid #3d3d3d;'>"
    "<h3 align='center' style='color: #007acc;'>Navegação 2D (MPR)</h3>"
    "<ul style='line-height: 1.6;'>"
    "<li><b>Botão Esquerdo (Fundo):</b> Ajuste de Contraste</li>"
    "<li><b>Botão Esquerdo (Linhas):</b> Arrastar fatias / Espessura MIP</li>"
    "<li><b>Scroll (Roda):</b> Navegar entre Fatias</li>"
    "<li><b>Botão do Meio:</b> Mover a Imagem (Pan)</li>"
    "<li><b>Botão Direito:</b> Zoom In / Out</li>"
    "<li><b>Duplo-Clique:</b> Maximizar Tela</li>"
    "<li><b>Crosshair:</b> Segure a letra <b>\"C\"</b> ou ative o botão para sincronizar as telas</li>"
    "</ul>"
    "</td>"
    "<td width='50%' valign='top'>"
    "<h3 align='center' style='color: #e74c3c;'>Navegação 3D (Volume)</h3>"
    "<ul style='line-height: 1.6;'>"
    "<li><b>Botão Esquerdo:</b> Rotacionar o modelo 3D</li>"
    "<li><b style='color: #f1c40f;'>Shift + Esquerdo:</b> Janelamento 3D (Transparência)</li>"
    "<li><b>Botão do Meio:</b> Mover o modelo 3D (Pan)</li>"
    "<li><b>Botão Direito:</b> Zoom In / Out</li>"
    "<li><b>Duplo-Clique:</b> Maximizar Tela</li>"
    "</ul>"
    "</td>"
    "</tr>"
    "</table>"
    "</div>"
)

HTML_DICAS_NAVEGACAO_EN = (
    "<div style='color: #aaaaaa;'>"
    "<table width='100%' align='center' cellpadding='15' style='border-collapse: collapse;'>"
    "<tr>"
    "<td width='50%' valign='top' style='border-right: 1px solid #3d3d3d;'>"
    "<h3 align='center' style='color: #007acc;'>2D Navigation (MPR)</h3>"
    "<ul style='line-height: 1.6;'>"
    "<li><b>Left Button (Background):</b> Contrast Adjustment</li>"
    "<li><b>Left Button (Lines):</b> Drag slices / MIP Thickness</li>"
    "<li><b>Scroll (Wheel):</b> Navigate Slices</li>"
    "<li><b>Middle Button:</b> Pan Image</li>"
    "<li><b>Right Button:</b> Zoom In / Out</li>"
    "<li><b>Double-Click:</b> Maximize Viewport</li>"
    "<li><b>Crosshair:</b> Hold key <b>\"C\"</b> or enable button to sync viewports</li>"
    "</ul>"
    "</td>"
    "<td width='50%' valign='top'>"
    "<h3 align='center' style='color: #e74c3c;'>3D Navigation (Volume)</h3>"
    "<ul style='line-height: 1.6;'>"
    "<li><b>Left Button:</b> Rotate 3D Model</li>"
    "<li><b style='color: #f1c40f;'>Shift + Left:</b> 3D Windowing (Transparency)</li>"
    "<li><b>Middle Button:</b> Pan 3D Model</li>"
    "<li><b>Right Button:</b> Zoom In / Out</li>"
    "<li><b>Double-Click:</b> Maximize Viewport</li>"
    "</ul>"
    "</td>"
    "</tr>"
    "</table>"
    "</div>"
)

# Mapeia as chaves HTML finais baseadas no idioma

_tradutor_global.dicionario["label_dicas_navegacao"] = {
    "pt": HTML_DICAS_NAVEGACAO_PT,
    "en": HTML_DICAS_NAVEGACAO_EN
}
